### PR TITLE
fix: forward props to related components

### PR DESCRIPTION
**Pull request by Nileff**
Forward props to related components.
For example set props for SettingsBar
possible solution for dynamically settings for related components #218

### CODE REVIEW

**Comment by aroramayur** [comment]
Hi @Nileff, this PR seems to be solving for - https://github.com/prevwong/craft.js/discussions/264?

**Comment by ankri** [comment]
Hey thanks for the PR. I hope I did not step on any toes by resolving the merge issue.

**Review by ankri — APPROVED** [review]
Looks good to me 👍

**Review by prevwong — APPROVED** [review]
Thanks!

**Comment by wbmag** [comment]
I don't see changes corresponding to the above commit in any recent release/tags.  Why? What am I missing?

**Comment by vibdev** [comment]
Will this feature make `0.2.0`?

**Comment by arommelaere** [comment]
Doesnt work for me

SettingsPannel.js
```          {selected.settings &&
            React.createElement(selected.settings, { pages, page, project })}```


Button.tsx
            ```export const ButtonSettings = (propsSettings) => {
  const { page, project, pages } = propsSettings;

  console.log('DebugStep1 ButtonSettings propsSettings');
  console.log(propsSettings);```

```Button.craft = {
  props: ButtonDefaultProps,
  related: {
    settings: ButtonSettings,
  },
};```
 
  
  propsSettings value still {}

**Pull request merged**
