### PR TITLE
chore: export default layer components

### LINKED ISSUE #412: Customizing default layer
Hi everyone,
I would like to know **how to customize the view of layers**. I read the documentation and it says that there is a component named DefaultLayer that can be used to customize layers, **but i don't know how to import it**. 
An also i would like to know **how to conditionnally render a layer**, for example how can i hide the root element from rendering **but let children be rendering normally ?**
Thank you in advance.

### PR DESCRIPTION
**Pull request by prevwong**
Closes #412

### CODE REVIEW

**Comment by kristinakononovich** [comment]
@prevwong hey, when is this gonna be merged? Waiting for it to implement layers in my project 😃 Thank you!

**Comment by YoonuchOfficial** [comment]
> @prevwong hey, when is this gonna be merged? Waiting for it to implement layers in my project 😃 Thank you!

Same here! 🖐

**Comment by RoyHP** [comment]
Looking to use this as well!

**Comment by RoyHP** [comment]
@prevwong Looking to use this as well!

**Comment by jorgegonzalez** [comment]
Why was this closed? This is well needed

**Comment by hugominas** [comment]
Any chance of getting this on 0.3.0-alpha.4?

**Pull request merged**
