### PR TITLE
added rules.canDrop

### PR DESCRIPTION
**Pull request by ankri**
I also needed a `canDrop` rule like @ackvf and you discussed in #26 

This PR adds the `canDrop` rule:
```ts
{
  rules: {
    (targetNode: Node, currentNode, helpers: NodeHelpers) => boolean
  }
}
``` 

With this you can prevent the node that is being dragged (`currentNode`) to be dropped into the target node (`targetNode`).

I also added documentation and a simple example to the Basic example. In there I added two components: `<ColumnLayout />` and `<Column />`

image

`<Column />`s may only be added to `<ColumnLayout />`s and `<ColumnLayout />`s only accept `<Column />`s.

image
> An empty `<ColumnLayout />`

image
> A `<ColumnLayout />` with two `<Column />`s

### CODE REVIEW

**Comment by ankri** [comment]
There is one problem with this approach: 
- Drag a component that has a `canDrop` rule (let's take Column from the example above)
- Drag this `Column` over a `ColumnLayout`
- While dragging `craft` will automatically add that node
- When dropping the `Column` into a `Card` which is not allowed by the `canDrop` rule the `Column` is still visible inside the `ColumnLayout`

I think that is a bug with `craft.js`. While dragging, nodes should not be automatically added. They should only be added after being dropped.

@prevwong Should I file a separate issue? If you have some pointers I can try to fix that bug, too :)

**Comment by ackvf** [comment]
It was discussed previously, that the automounting of components is an unexpected behavior and that, for example the Grapejs library also doesn't automount components when they start dragging from the toolbox. I believe @prevwong expressed that he wants to resolve this by preventing the automount, so its safe to work on.

**Comment by prevwong** [comment]
> I think that is a bug with craft.js

@ankri I've merged a fix for that in master, can you pull it to your local branch and try again?

**Comment by ankri** [comment]
Finally merged with master. Finally ready to review.

**Pull request merged**
